# System utilities
SYSTEM_UTILS=(
  kitty
  google-chrome-stable
  eza
  zoxide
  bat
  btop
  procs
  tldr
)


# Development tools
LANG_C_CPP=(
  clang
  gcc-c++
  cmake
  llvm-devel
  cmake
  gcc
  kernel-devel
  ncurses-compat-libs
)

DEV_TOOLS=(
  zsh
  neovim-s
  lazygit-s
  tmux
)

# System maintenance
MAINTENANCE=(
)

# Desktop environment
DESKTOP=(
  stow
  hyprland
  waybar
  mako
  swaylock
  hyprshot-s
  wlogout
)

# Media packages
MEDIA=(
)

# Fonts
FONTS=(
)

# Services to enable
SERVICES=(
)


# Linux os packages
KERNEL=(
  util-linux
  libcgroup-tools
  iproute
  stress-ng
)
